export default {
  INCREMENT_NUM_VAL     : 'INCREMENT_NUM_VAL',
  DECREMENT_NUM_VAL     : 'DECREMENT_NUM_VAL',
  INITIALIZE_NUM_VAL    : 'INITIALIZE_NUM_VAL',
  UPDATE_TODO_ITEM      : 'UPDATE_TODO_ITEM',
  CREATE_NEW_TODO_ITEM  : 'CREATE_NEW_TODO_ITEM',
  INITIALIZE_TODO_LIST  : 'INITIALIZE_TODO_LIST',
  
  MANAGE_EDIT_TASK      : 'MANAGE_EDIT_TASK',
  MANAGE_DELETE_TASK    : 'MANAGE_DELETE_TASK',
  MANAGE_COMPLETE_TASK  : 'MANAGE_COMPLETE_TASK',
};